/*(histogram) Write a program which will draw the histogram for n integers from 0 to 99.
N is input by the user. Each of the n numbers will be generated by calling rand() % 100.
The program will consist of two functions (i) to collect the frequency distribution of the
numbers (ii) to print the histogram.*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define NUM_BUCKETS 10

void collectFrequencyDistributions(int *freq, int n);
void printHistogram(const int *freq);

int main()
{
    int amt = 0;
    
    // Seed the random number generator
    srand((unsigned)time(NULL));

    printf("Please input the number of values you want generated:\n");
    if (scanf("%d", &amt) != 1 || amt<0) {
        printf("Invalid input.\n");
        return 1;
    }

    int *freqArray = malloc(NUM_BUCKETS*sizeof(int));

    if (freqArray == NULL) {
        fprintf(stderr, "Memory allocation failed.\n");
        return 1;
    }

    for (int i = 0; i < NUM_BUCKETS; i++) {
        *(freqArray + i) = 0;
    }

    collectFrequencyDistributions(freqArray, amt);
    printHistogram(freqArray);

    free(freqArray);

    return 0;

}

void collectFrequencyDistributions(int *freq, int n){
    int i, randomNumber, bucket;
    for (int i = 0; i < n; i++){
        randomNumber = rand() % 100; // Gernerate a number between 0 and 99
        bucket = randomNumber / 10;
        freq[bucket]++;
    }
    return;
}
void printHistogram(const int *freq){
    const int *ptr = freq;
    for (int i = 0; i < NUM_BUCKETS; i++){
        int lowerBounds = i*10;
        int upperBounds = lowerBounds + 9;
        printf("%2d - %2d  |", lowerBounds, upperBounds);
        for (int j = 0; j < *(ptr + i); j++){
            printf("*");
        }
        printf("\n");
    }
}